version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - python3 _docs/build_all_docs.py

python:
  install:
    - requirements: _docs/requirements.txt


sphinx:
  configuration: _docs/conf.py

formats:
  - pdf


